---
apiVersion: v1
kind: Service
metadata:
  name: snyk-juice-shop
  labels:
    app: snyk-juice-shop
spec:
  ports:
    - port: 8081
      targetPort: 3001
      protocol: TCP
  selector:
    app: snyk-juice-shop
  type: LoadBalancer
    